version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test-db
    ports:
    - "5438:5432"
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  # test_frontend:
  #   build: './web'
  #   ports:
  #   - "4204:4204"

  test_backend:
    build: './typescript-backend'
    depends_on:
      - postgres
    ports:
    - "4201:4201"

